# Generated by Django 3.2.8 on 2021-10-27 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atracao',
            old_name='idade_min',
            new_name='idade_minima',
        ),
    ]
