# Generated by Django 3.2.8 on 2021-10-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('atracoes', '0002_rename_idade_min_atracao_idade_minima'),
    ]

    operations = [
        migrations.AddField(
            model_name='atracao',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='atracoes'),
        ),
    ]
